<?php

declare(strict_types=1);

namespace EntreRedes\Cambios\Plazas;

/**
 * Pure, WordPress-free CSV parsing for the plaza backfill importer
 * (`Plazas\PlazaImporter`) — no `\wpdb`, no globals, no I/O of its own. This
 * class only turns CSV text already read from disk into plain arrays; it
 * never opens a file itself, so it is exercised directly in PHPUnit without
 * the SQLite test shim `Plazas\PlazaImporter` itself needs.
 *
 * *** THE FOUR COLUMNS, AND WHY ONLY THESE FOUR ***
 * `equipo`, `titular`, `tipo`, `puntaje_techo` are exactly the four values
 * `Plazas\PlazaRepository::openPlaza()` needs per plaza that are NOT already
 * fixed for the whole backfill. `season_id` and `fecha_desde_id` are
 * deliberately NOT columns — see `Plazas\PlazaImporter`'s class docblock for
 * why repeating them on every row would only multiply the chances of a
 * typo. A row's own line number (1-indexed, header is line 1, so the first
 * data row is line 2) stands in for a "fila" column: it is already unique,
 * already visible to whoever opens the CSV in a spreadsheet, and never needs
 * its own value the operator could get wrong.
 *
 * *** HEADER MATCHING IS BY NAME, CASE-INSENSITIVE AND ORDER-FREE ***
 * The four required columns may appear in any order, and EXTRA columns
 * (e.g. a `notas` column the process owner adds for their own bookkeeping)
 * are accepted and ignored — this file is filled by hand in a spreadsheet
 * app, not generated by this codebase, so the header contract only demands
 * "the four names this class needs are present somewhere", never "and
 * nothing else".
 *
 * *** COMMENTED EXAMPLE ROWS ***
 * Any data row whose FIRST cell starts with `#` (after trimming whitespace)
 * is skipped entirely — never parsed, never counted, never validated. This
 * is the mechanism `templates/plazas-import-template.csv` uses for its
 * worked examples: a process owner can leave them in place, or delete them,
 * without either choice affecting a real import.
 *
 * *** BLANK ROWS ***
 * A row where every cell is empty after trimming (the common trailing blank
 * line a spreadsheet export leaves behind) is skipped the same way.
 */
final class PlazaImportCsvParser {

    /**
     * The four column names this importer requires, exactly as they must
     * appear in the CSV header (matched case-insensitively, see class
     * docblock). Public so `Plazas\PlazaImporter` and the CLI tool can both
     * refer to the same list — e.g. for a `--help` usage message — without
     * duplicating it.
     */
    public const REQUIRED_COLUMNS = [ 'equipo', 'titular', 'tipo', 'puntaje_techo' ];

    /**
     * @return array<int, array{line:int, equipo:string, titular:string, tipo:string, puntaje_techo:string}>
     *         One entry per DATA row that survived comment/blank skipping,
     *         in file order. `line` is the 1-indexed physical line number in
     *         the source CSV (the header is line 1), for every later error
     *         message to name.
     * @throws \InvalidArgumentException When the file is empty, or the
     *         header is missing one of `self::REQUIRED_COLUMNS`.
     */
    public static function parse( string $csvContent ): array {
        // A UTF-8 BOM is common in a file exported from Excel — strip it so
        // it never becomes part of the first header cell's name.
        $csvContent = preg_replace( '/^\xEF\xBB\xBF/', '', $csvContent ) ?? $csvContent;

        $lines = preg_split( "/\r\n|\r|\n/", $csvContent );
        if ( false === $lines ) {
            $lines = [];
        }

        // Trailing blank line from a final newline — never a real header.
        if ( [] !== $lines && '' === trim( (string) end( $lines ) ) ) {
            array_pop( $lines );
        }

        if ( [] === $lines ) {
            throw new \InvalidArgumentException(
                'PlazaImportCsvParser::parse(): the CSV file is empty — it needs at least a header row.'
            );
        }

        $headerCells = str_getcsv( (string) $lines[0], ',', '"', '\\' );
        $columnIndex = self::indexHeader( $headerCells );

        $rows = [];

        for ( $i = 1, $count = count( $lines ); $i < $count; $i++ ) {
            $lineNumber = $i + 1; // 1-indexed, header is line 1.
            $rawLine    = (string) $lines[ $i ];

            if ( '' === trim( $rawLine ) ) {
                continue;
            }

            $cells = str_getcsv( $rawLine, ',', '"', '\\' );

            if ( self::isCommentRow( $cells ) ) {
                continue;
            }

            $rows[] = [
                'line'          => $lineNumber,
                'equipo'        => self::cell( $cells, $columnIndex['equipo'] ),
                'titular'       => self::cell( $cells, $columnIndex['titular'] ),
                'tipo'          => self::cell( $cells, $columnIndex['tipo'] ),
                'puntaje_techo' => self::cell( $cells, $columnIndex['puntaje_techo'] ),
            ];
        }

        return $rows;
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /**
     * @param array<int, string|null> $headerCells
     * @return array<string, int> REQUIRED_COLUMNS name -> its column index.
     * @throws \InvalidArgumentException When a required column is missing.
     */
    private static function indexHeader( array $headerCells ): array {
        $byName = [];
        foreach ( $headerCells as $index => $cell ) {
            $byName[ strtolower( trim( (string) $cell ) ) ] = $index;
        }

        $columnIndex = [];
        $missing     = [];

        foreach ( self::REQUIRED_COLUMNS as $name ) {
            if ( ! array_key_exists( $name, $byName ) ) {
                $missing[] = $name;
                continue;
            }
            $columnIndex[ $name ] = $byName[ $name ];
        }

        if ( [] !== $missing ) {
            throw new \InvalidArgumentException(
                'PlazaImportCsvParser::parse(): the CSV header is missing required column(s): '
                . implode( ', ', $missing ) . '. Required columns are: '
                . implode( ', ', self::REQUIRED_COLUMNS ) . '.'
            );
        }

        return $columnIndex;
    }

    /**
     * @param array<int, string|null> $cells
     */
    private static function isCommentRow( array $cells ): bool {
        $first = trim( (string) ( $cells[0] ?? '' ) );

        return str_starts_with( $first, '#' );
    }

    /**
     * @param array<int, string|null> $cells
     */
    private static function cell( array $cells, int $index ): string {
        return trim( (string) ( $cells[ $index ] ?? '' ) );
    }
}
